version: '3'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: db1
      POSTGRES_USER: porgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db-1.cpu6hihqwkae.us-east-1.rds.amazonaws.com 
      POSTGRES_PORT: 5432

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db